name: secure_password_utility
description: This password utility encourages the use of strong passwords in flutter apps.
version: 1.0.2
homepage: https://www.inspiratixhub.com
repository: https://github.com/michaeloki/secure-password-utility-flutter

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0
assets:
  - assets/

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
